name: Action Test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  local-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        if: ${{ !env.ACT }}
        with:
          node-version: 16
          cache: npm
      - uses: actions/setup-node@v2
        if: ${{ env.ACT }}
        with:
          node-version: 16
      - name: Install
        run: npm install --prefer-offline
      - name: Build
        run: npm run build
